version: '3.1'
services:
  postgresql:
    image: postgres:16.1
    container_name: postgres-compose
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - 5432:5432
