version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-compose
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBIT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBIT_PASS
    volumes:
      - "$DOCKER_VOLUME_ROOT/rabbitmq:/var/lib/rabbitmq"