version: "3"
services:
  mongo:
    image: mongo:4
    container_name: mongo-compose
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - "$DOCKER_VOLUME_ROOT/mongo/mongo-data:/data/db"
      - "$DOCKER_VOLUME_ROOT/mongo/mongod.conf.orig:/etc/mongod.conf.orig"
    ports:
      - 27017:27017
